-- ====================================================================
-- ESQUEMA DE BASE DE DATOS EXACTO (PLAYERS, MATCHES, MATCH_MOVES)
-- Basado en el diagrama de entidad-relación de Supabase
-- ====================================================================

-- 1. TABLA: players (Jugadores y Ranking)
CREATE TABLE IF NOT EXISTS public.players (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nickname TEXT UNIQUE NOT NULL,
    games_played INT4 NOT NULL DEFAULT 0,
    wins INT4 NOT NULL DEFAULT 0,
    losses INT4 NOT NULL DEFAULT 0,
    ties INT4 NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_played_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para el ranking
CREATE INDEX IF NOT EXISTS idx_players_wins_games 
ON public.players (wins DESC, games_played ASC);

-- 2. TABLA: matches (Partidas)
CREATE TABLE IF NOT EXISTS public.matches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    game_mode TEXT NOT NULL DEFAULT 'pvp',
    player_x_name TEXT NOT NULL DEFAULT 'Jugador X',
    player_o_name TEXT NOT NULL DEFAULT 'Jugador O',
    winner TEXT NOT NULL,
    total_moves INT4 NOT NULL,
    duration_seconds INT4 NOT NULL DEFAULT 0,
    final_board TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_matches_created_at 
ON public.matches (created_at DESC);

-- 3. TABLA: match_moves (Movimientos jugada a jugada)
CREATE TABLE IF NOT EXISTS public.match_moves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id UUID NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
    move_number INT4 NOT NULL,
    player CHAR(1) NOT NULL,
    cell_index INT4 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_match_moves_match_id 
ON public.match_moves (match_id, move_number ASC);

-- 4. HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_moves ENABLE ROW LEVEL SECURITY;

-- 5. POLÍTICAS DE ACCESO PÚBLICO (ANON Y AUTHENTICATED)

-- Políticas para players
DROP POLICY IF EXISTS "Permitir lectura publica de players" ON public.players;
CREATE POLICY "Permitir lectura publica de players"
ON public.players FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "Permitir insercion y actualizacion publica de players" ON public.players;
CREATE POLICY "Permitir insercion y actualizacion publica de players"
ON public.players FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- Políticas para matches
DROP POLICY IF EXISTS "Permitir lectura publica de matches" ON public.matches;
CREATE POLICY "Permitir lectura publica de matches"
ON public.matches FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "Permitir insercion publica de matches" ON public.matches;
CREATE POLICY "Permitir insercion publica de matches"
ON public.matches FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- Políticas para match_moves
DROP POLICY IF EXISTS "Permitir lectura publica de match_moves" ON public.match_moves;
CREATE POLICY "Permitir lectura publica de match_moves"
ON public.match_moves FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "Permitir insercion publica de match_moves" ON public.match_moves;
CREATE POLICY "Permitir insercion publica de match_moves"
ON public.match_moves FOR INSERT
TO anon, authenticated
WITH CHECK (true);
